class UnexpectedError(Exception):
    ...

class AbstractError(Exception):
    ...

class FieldRequirementException(Exception):
    ...

class ValidationError(Exception):
    ...

class NativeValidationError(Exception):
    ...

class ExcludeValue(Exception):
    ...